services:
  mariadb:
    container_name: mariadb
    build: ./mariadb
    image: mariadb
    volumes:
      - mariadb_v:/var/lib/mysql
    env_file:
      - .env
    networks:
      - app_net
    restart: always

  wordpress:
    container_name: wordpress
    build: ./wordpress
    image: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress_v:/var/www/html
    env_file:
      - .env
    networks:
      - app_net
    restart: always

  nginx:
    container_name: nginx
    build: ./nginx
    image: nginx
    depends_on:
      - wordpress
    # Expose HTTPS port to the host
    ports:
      - "443:443"
    volumes:
      - wordpress_v:/var/www/html
    env_file:
      - .env
    networks:
      - app_net
    restart: always

volumes:
  mariadb_v:
    driver: local
    driver_opts: # driver_opts utiliser ici pour configurer le Bind Mount
      type: none
      device: /home/tmilin/data/mysql #Docker va chercher ou cree ce dossier sur le disque pour stocker les donnees
      o: bind # o pour "option", bind est l'option qui fait que ca stock en temps reel les donneees
  wordpress_v:
    driver: local
    driver_opts:
      type: none
      device: /home/tmilin/data/wordpress
      o: bind

networks:
  app_net:
    driver: bridge
